name: Python Hello World

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger this workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # This action checks out your repository's code

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Run Python Hello World
      run: python -c "print('Hello, World!')"

